# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0002_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
