# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 23:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carrinho', '0003_auto_20160715_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_street', models.CharField(max_length=256)),
                ('address_number', models.CharField(max_length=16)),
                ('address_cep', models.CharField(max_length=8)),
                ('address_city', models.CharField(max_length=128)),
                ('address_state', models.CharField(max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
